enabled_layouts splits,stack
cursor_blink_interval 0
update_check_interval 0
macos_titlebar_color background
macos_option_as_alt yes
remember_window_size yes
initial_window_width 900
initial_window_height 600
allow_remote_control yes

font_family JetBrains Mono
font_size 12
background #222436
foreground #c8d3f5
selection_background #2d3f76
selection_foreground #c8d3f5
url_color #4fd6be
cursor #c8d3f5
cursor_text_color #222436
window_padding_width 5 10
# Tabs
active_tab_background #82aaff
active_tab_foreground #1e2030
inactive_tab_background #2f334d
inactive_tab_foreground #545c7e
#tab_bar_background #1b1d2b

# Windows
active_border_color #82aaff
inactive_border_color #2f334d

color0 #1b1d2b
color1 #ff757f
color2 #c3e88d
color3 #ffc777
color4 #82aaff
color5 #7c5fbf
color6 #86e1fc
color7 #c7c7c7

color8  #444a73
color9  #ff8d94
color10 #c7fb6d
color11 #ffd8ab
color12 #9ab8ff
color13 #caabff
color14 #b2ebff
color15 #c8d3f5

color16 #ff966c
color17 #c53b53

active_tab_font_style   bold
inactive_tab_font_style normal

tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 1
tab_title_max_length 20
tab_bar_margin_width 2
tab_title_template " [{index}] {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"

map cmd+= no-op

map cmd+shift+h open_url_with_hints

map cmd+\ launch --cwd=current --location=vsplit
map cmd+- launch --cwd=current --location=hsplit

map cmd+shift+j neighboring_window left
map cmd+shift+l neighboring_window right
map cmd+shift+i neighboring_window up
map cmd+shift+k neighboring_window down

map cmd+s swap_with_window
map cmd+z toggle_layout stack
map cmd+x close_window_with_confirmation

map cmd+left resize_window narrower 5
map cmd+right resize_window wider 5
map cmd+up resize_window taller 5
map cmd+down resize_window shorter 5

map cmd+d detach_window new-tab

map cmd+j previous_tab
map cmd+l next_tab

map cmd+[ previous_tab
map cmd+] next_tab

map cmd+r set_tab_title

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

# Ctrl 0 - 9
map ctrl+0 send_text all \x1b[48;5u
map ctrl+1 send_text all \x1b[49;5u
map ctrl+2 send_text all \x1b[50;5u
map ctrl+3 send_text all \x1b[51;5u
map ctrl+4 send_text all \x1b[52;5u
map ctrl+5 send_text all \x1b[53;5u
map ctrl+6 send_text all \x1b[54;5u
map ctrl+7 send_text all \x1b[55;5u
map ctrl+8 send_text all \x1b[56;5u
map ctrl+9 send_text all \x1b[57;5u

# Ctrl + . , ;
map ctrl+. send_text all \x1b[46;5u
map ctrl+, send_text all \x1b[44;5u
map ctrl+; send_text all \x1b[59;5u

# Shift + Enter
map shift+enter send_text all \x1b[13;2u

# Ctrl + I / M
map ctrl+i send_text all \x1b[105;5u
map ctrl+m send_text all \x1b[109;5u

# Ctrl + Shift Remaps
map ctrl+shift+h send_text all \x1b[72;6u
map ctrl+shift+j send_text all \x1b[74;6u
map ctrl+shift+k send_text all \x1b[75;6u
map ctrl+shift+l send_text all \x1b[76;6u
map ctrl+shift+u send_text all \x1b[117;6u
map ctrl+shift+o send_text all \x1b[111;6u
map ctrl+shift+p send_text all \x1b[112;6u
map ctrl+shift+s send_text all \x1b[108;6u

mouse_map left click ungrabbed no-op
mouse_map cmd+left click ungrabbed mouse_handle_click selection link prompt
mouse_map cmd+left press ungrabbed mouse_selection normal

url_style straight
