# Brewfile - Dotfiles Dependencies
# Install: brew bundle --file=Brewfile

tap "asmvik/formulae"

cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-symbols-only-nerd-font"
brew "fd"
brew "ripgrep"
brew "fzf"
brew "bat"
brew "eza"
brew "zoxide"
brew "jq"
brew "tree"
brew "curl"
brew "wget"
brew "stow"
brew "gum"
brew "git-delta"
brew "ydiff"
brew "difftastic"

brew "zsh" unless system("/usr/bin/which", "zsh", out: File::NULL)
cask "ghostty"
cask "kitty"
brew "asmvik/formulae/skhd"
brew "tmux"
brew "neovim"
brew "cmake"
brew "luarocks"
brew "tree-sitter-cli"
brew "lua-language-server"
brew "stylua"
brew "luacheck"
brew "yazi"
brew "ffmpeg"
brew "imagemagick"
brew "poppler"
brew "resvg"
brew "sevenzip"
brew "exiftool"
brew "mediainfo"
brew "taplo"
brew "gnu-tar"
brew "lazygit"
brew "starship"
brew "opencode"
brew "go"
brew "uv"
brew "node"
